### ISSUE TITLE
Older get-pip.py version not available

### ISSUE THREAD

**Issue by JunielKatarn** [pypa/get-pip#119]
Trying to install PIP for Python 2.7, but the older links don't seem to work:

```
$ wget https://bootstrap.pypa.io/2.7/get-pip.py
--2021-06-30 19:06:29--  https://bootstrap.pypa.io/2.7/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.52.175, 23.235.32.32, 104.156.80.32, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.52.175|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-30 19:06:29 ERROR 404: Not Found.
```

**Comment by pirogoeth** [comment]
All of the "elder" Python series links for get-pip.py at the top level are 404ing. It seems that there are some deeper links available at `https://bootstrap.pypa.io/pip/{{python_series}}/get-pip.py`.

**Comment by pradyunsg** [comment]
There's extended discussion about this in #61 and #115. Notably, please do read the contents of moved.py in #115.
