### ISSUE TITLE
With the new version of wheel 0.30 there isn't support for 2.6 anymore

### ISSUE THREAD

**Issue by babineaum** [pypa/get-pip#12]
we might be those slackers bringing up the rear but with the install of wheel that comes by default with get-pip.py, the new 0.30 version of wheel doesn't support 2.6 anymore.

taken from 0.30.0 release notes https://pypi.python.org/pypi/wheel#downloads 
`Removed support for Python 2.6, 3.2 and 3.3.`

Is it possible to hardcode the 0.29 version of wheel in the install? thanks.

**Comment by xavfernandez** [comment]
`python get-pip.py wheel==0.29` should work I think.

**Comment by babineaum** [comment]
thanks! that notation isn't readily available in the installation notes.

**Comment by ewdurbin** [comment]
added documentation in https://github.com/pypa/pip/pull/5075

**Comment by dstufft** [comment]
This should be resolved now, the ``get-pip.py`` will pin wheel and setuptools when they drop support for a version of Python as well.
