### ISSUE TITLE
bootstrap.pypa.io/3.X/get-pip.py results in a 404, despite having a directory listings (& having previously worked).

### ISSUE THREAD

**Issue by jaketeater** [pypa/get-pip#120]
https://bootstrap.pypa.io/3.4/get-pip.py returns a 404.

If you browse to https://bootstrap.pypa.io/3.4/ the get-pip.py file is listed. However, it returns a 404.

The /3.4 directory is listed at:
https://bootstrap.pypa.io/

This holds true to all of the https://bootstrap.pypa.io/2.X and https://bootstrap.pypa.io/3.X that I tested.

I was able to access the file here, and updated my code with this URL.
https://bootstrap.pypa.io/pip/3.4/get-pip.py

**Comment by pradyunsg** [comment]
See #61 and #115.

**Comment by pradyunsg** [comment]
> If you browse to https://bootstrap.pypa.io/3.4/ the get-pip.py file is listed. However, it returns a 404.

Actually, this is interesting! @ewdurbin could you take a look into this?

**Comment by ewdurbin** [comment]
Broken symlinks that should have been removed after the migration.

<img width="566" alt="Screen Shot 2021-07-02 at 12 52 15 PM" src="https://user-images.githubusercontent.com/1200832/124306411-5d001180-db34-11eb-82c5-50cafd7a1dc4.png">

They're gone now!

**Comment by ewdurbin** [comment]
OK, and the automation that creates them is also gone 😅 https://github.com/python/psf-salt/commit/134bedbae45ba15cae54d1ff3da5674116b2f7a2

**Comment by pradyunsg** [comment]
Thanks @ewdurbin! ^.^
