### ISSUE TITLE
Whitelisting URLs required?

### ISSUE THREAD

**Issue by lppier** [pypa/get-pip#125]
Hi, I'm trying to get get-pip to work in order to resolve a python vulnerability in my containers. 
The urls I've whitelisted are as follows : 
https://bootstrap.pypa.io/     
https://pypi.org/simple/pip/

I also recently realised that the following url is required to be whitelisted. 
https://files.pythonhosted.org/

Are there any others that I should know of? 

Thank you.

**Comment by xavfernandez** [comment]
No, I think that's the only 3 needed.
