### ISSUE TITLE
Version 21.2.4

### ISSUE THREAD

**Issue by cobaltgit** [pypa/get-pip#126]
Just wondering, when will there be a new get-pip that installs version 21.2.4. I'm asking because me and someone else are making a Docker image with the latest versions of python and pip compiled from source, which is actually slimmer than the official image.

**Comment by pradyunsg** [comment]
@uranusjr ^

**Comment by uranusjr** [comment]
Oops, I dropped the ball when I decided to skip 21.2.4 from ensurepip. I’ll submit a PR now.

**Comment by uranusjr** [comment]
Released via #128
