### ISSUE TITLE
[Feature request] Generate get-pip.py from local pip wheel or local pip project

### ISSUE THREAD

**Issue by Mark-Joy** [pypa/get-pip#134]
Supposed I had a locally clone `pip` project, did some changes on the source code. Now, I want to generate get-pip.py from it.
It would be great if `generate. py` can support this feature.
Thank you.

**Comment by pradyunsg** [comment]
Why is this necessary? What would be the point of doing this?

**Comment by Mark-Joy** [comment]
I would like to use some simple customized `pip` features. 
So what I want to do is: generate `get-pip.py` from my local modified source or local wheel, host it on github/other host. wget and install when needed.
Rather convenient feature, isn't it?

**Comment by pradyunsg** [comment]
I don’t think there’s much use of that feature for anyone else, especially not for pip maintainers. I don’t think adapting the generation logic that sits in this repository, to do what you want to, has much value for the people who maintain pip (who are the primary audience for the generation logic).

You’re welcome to fork this repository and modify the generate.py script to fit your needs. You’re already doing that for pip.
