### ISSUE TITLE
python outputs python 

### ISSUE THREAD

**Issue by stripov1337** [pypa/get-pip#135]
PS C:\Users\Story\Desktop\1> python3 get-pip.py
Python
why?

**Comment by benda1313** [comment]
You should run pip install using:

python get-pip.py

**Comment by pradyunsg** [comment]
This might be due to the Windows story integration? /cc @zooba

**Comment by zooba** [comment]
It should print out a longer message if it's the redirection stub, telling you that Python isn't installed and how to get it. No idea why the message is being cut short, but I believe it starts with "Python [is not available...]" and so this seems most likely.

The regular installer has only ever added `python.exe` to PATH. You only get `python3` from a Store install, so if @stripov1337 has installed from python.org (or is in a virtual environment) then using `python get-pip.py` is indeed the right solution.
