### ISSUE TITLE
import of setuptools causes problems

### ISSUE THREAD

**Issue by jaraco** [pypa/get-pip#137]
get-pip during its initialization will check to see if setuptools is installed by invoking `import setuptools`. For various historical reasons, importing setuptools is expensive and messy.

In pypa/setuptools#2993, an issue was reported illustrating a conflict between setuptools expectation on import and the need to avoid making that expectation for pip.

I believe the best workaround for this situation would be to avoid importing setuptools at all. Maybe just invoke the "finder" or "get_spec" for setuptools but not actually load/run it. Or consider inspecting the metadata to see if a "setuptools" package is present (may require Python 3.8).

**Comment by pradyunsg** [comment]
PRs would be welcome! :)

**Comment by Stikus** [comment]
Hello, looks like here is PR: https://github.com/pypa/get-pip/pull/140

Can you merge it if everything ok?

Some scripts using `get-pip` struggling until fix is in place. Like https://github.com/google/deepvariant

**Comment by pradyunsg** [comment]
Closing since 22.0.x uses a less invasive mechanism.

**Comment by tp-drosssmith** [comment]
in this sentence "i asked colin if they were trying to broadcom us. they said no" is broadcom a verb, adverb or something else?
