### ISSUE TITLE
Get-pip for cellular devices 

### ISSUE THREAD

**Issue by Mpuminene** [pypa/get-pip#138]
The javascript is has many irrelevant point of features. It isn’t user friendly, as there is no Love 2D function.

**Comment by pradyunsg** [comment]
Hi there! Could you clarify what this is about?

This project is about hosting https://bootstrap.pypa.io/pip/, which does not seem to be related to what you've posted.

**Comment by Mpuminene** [comment]
The host should be

**Comment by Mpuminene** [comment]
Pip’s organisation is perceived to be automated, yet the host needs control from plauery

**Comment by Mpuminene** [comment]
Pip’s organisation is perceived to be automated, yet the host needs control from player

**Comment by Mpuminene** [comment]
get-pip.py organisation is perceived to be automated, yet the host needs control from player
