### ISSUE TITLE
Powerup 

### ISSUE THREAD

**Issue by Mpuminene** [pypa/get-pip#139]
Love.graphics.draw

**Comment by pradyunsg** [comment]
Hi there!

Are you referring to https://love2d.org/wiki/love.graphics.draw? If so, I recommend getting in touch with these folks over at https://love2d.org -- specifically, they link to https://love2d.org/forums/, [this Discord server](https://discord.gg/rhUets9) and this [internet relay chat room](https://webchat.oftc.net/?channels=love) (Live Chat).

**Comment by pradyunsg** [comment]
x-ref: #138, for my fellow maintainers

**Comment by Mpuminene** [comment]
love.graphics.draw should be the love2D implemented in main.lua

**Comment by pradyunsg** [comment]
Please reach out to the folks over at https://webchat.oftc.net/?channels=love
