### ISSUE TITLE
"get-pip.py --help" should state that it also accepts pip's arguments

### ISSUE THREAD

**Issue by ian-kelling** [pypa/get-pip#148]
It is currently misleading, suggesting that there are only 3 possible arguments. It's output is:

```
usage: tmp.KSkiMEIr0k [-h] [--no-setuptools] [--no-wheel]

optional arguments:
  -h, --help       show this help message and exit
  --no-setuptools
  --no-wheel
```

**Comment by ian-kelling** [comment]
Note, in my original comment "tmp.KSkiMEIr0k" is just a temporary name for the file I used.

**Comment by pradyunsg** [comment]
A PR for this would be welcome. :)

**Comment by pradyunsg** [comment]
Closing this since there doesn't seem to be much interest in actually doing this, expressed by anyone.
