### ISSUE TITLE
Don't refer to non-existent get-pip versions

### ISSUE THREAD

**Issue by solarkraft** [pypa/get-pip#149]
I've lately been messing around with Python 3.1, trying to get PIP. The installation script errors out with

> ERROR: This script does not work on Python 3.1 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.1/get-pip.py instead.

So naturally I tried to find get-pip for Python 3.1, considering that I've just been told that it exists. 

Thankfully this _lie_ was eventually [cleared up](https://github.com/pypa/get-pip/issues/61#issuecomment-1044114035):

> We've never had a get-pip.py for Python 3.1. 

It turns out that [this code](https://github.com/pypa/get-pip/blob/9adbfbd3778332c49acffc18150e9a2407028b93/templates/default.py#L27) only takes the current version of Python you're running and generates a get-pip link for it. 
```
if this_python < min_version:
    message_parts = [
        "This script does not work on Python {{}}.{{}}".format(*this_python),
        "The minimum supported Python version is {{}}.{{}}.".format(*min_version),
        "Please use https://bootstrap.pypa.io/pip/{{}}.{{}}/get-pip.py instead.".format(*this_python),
    ]
    print("ERROR: " + " ".join(message_parts))
```

It would probably better be changed to avoid unnecessarily confusing users by pointing at get-pip versions that don't exist.

**Comment by pradyunsg** [comment]
Uhm... Why are you trying to use Python 3.1?

**Comment by pradyunsg** [comment]
I don't think it's worth trying to have a better error message on EoL Python versions.

**Comment by pradyunsg** [comment]
Python 3.1 typically has 0 downloads from PyPI on a given date, occasionally bumping up to something higher like 3. It bumped up to 185 yesterday, which I imagine was you. :)

https://pypistats.org/packages/__all__

I don't think there's too many others.

**Comment by pradyunsg** [comment]
Closing this as a wontfix, because I'm not interested in an extended discussion here. If some other pip maintainer thinks this is worth their time, please feel free to reopen.
