### ISSUE TITLE
python 3.9 embed + get-pip fail to install "parse"

### ISSUE THREAD

**Issue by sdementen** [pypa/get-pip#154]
hello

I have unzip the embeddable python 3.9.13 and ran get-pip to have pip (+setup+wheels) installed in it (ran flawlessly).
I changed the python39._pth to
```
python39.zip
.
Lib\site-packages

# Uncomment to run site.main() automatically
#import site
```

Running `"C:\...\python-3.9.13-embed-amd64\python.exe" -m pip install parse` fails with
```
Looking in indexes: https://.../simple
Collecting parse
  Downloading https://.../packages/packages/89/a1/82ce536be577ba09d4dcee45db58423a180873ad38a2d014d26ab7b7cb8a/parse-1.19.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\GFJ138\AppData\Local\Temp\pip-install-xr9q6zif\parse_13f575e990d242a08d7e3716be718acd\setup.py", line 7, in <module>
          from parse import __version__, __doc__
      ModuleNotFoundError: No module named 'parse'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I can successfully install other packages like 'six' with
```
Looking in indexes: https://.../simple
Collecting six
  Using cached https://.../packages/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
Successfully installed six-1.16.0
```

I could successfully install `parse` following the same procedure but python 3.8.10 (vs python 3.9.13).

**Comment by pradyunsg** [comment]
Hi!

This is a problem with the parse package. Please file an issue with them or your Python configuration, neither of which are issues with get-pip.py. Please file an issue on the parse project's issue tracker.

Also, see the note at the end.

**Comment by sdementen** [comment]
As I can pip install the parse package on a standard python 3.9 (not embedded, pip already available), I thought it would be due to a get-pip issue in the pyrhon- embeddable distribution

**Comment by pradyunsg** [comment]
Ah, I misunderstood. From https://docs.python.org/3/using/windows.html#the-embeddable-package:

> Third-party packages should be installed by the application installer alongside the embedded distribution. Using pip to manage dependencies as for a regular Python installation is not supported with this distribution [snip]

**Comment by sdementen** [comment]
It seems it is the python39.pth_ that is causing issues (https://stackoverflow.com/questions/50023869/script-directory-not-included-in-sys-path-when-a-pth-is-in-use).
With the python39.pth_, I see that python/pip does not add the path to the temporary folder where the package is extracted to the sys.path (ie the sys.path only includes the path in python39.pth_). 
When removing it, I see that python/pip adds the path to the temporary folder and so the setup.py is able to import the local .py file (here, the setup.py is importing the module parse.py to extract its version number).

So I removed python39.pth_ and now pip works properly with the python embeddable version.

Not sure why the presence of python39.pth_ changes the sys.path behavior of python/pip.
If I start the embeddable python with a python39.pth_, I can add items to sys.path and they are properly accounted for.
Maybe pip starts new python processes and set PYTHONPATH to include the temporary folder. And given (https://bugs.python.org/issue28245), the embeddable python is isolated and does not consider the PYTHONPATH  env variable.
If I remove python39.pth_, then it takes it into account the PYTHONPATH env variable.
