### ISSUE TITLE
curl: (60) SSL certificate problem

### ISSUE THREAD

**Issue by cybercat111** [pypa/get-pip#157]
When I was downloading the Ansible through the curl manager I've  got an error shared below:

$ curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
curl: (60) SSL certificate problem: self-signed certificate in certificate chain

How can I fix it without using a flag to disable a verification such as -k or --insecure?

**Comment by pradyunsg** [comment]
I'd suggest reaching out to someone in the organisation/network's IT team to help you with this.

See https://curl.se/docs/sslcerts.html for the documentation on curl (and, yes, -k could work -- I don't know your network setup).
