### ISSUE TITLE
Problem with the installation of PYQt5

### ISSUE THREAD

**Issue by ThanosOAA** [pypa/get-pip#165]
I'm running a Mac with the operating system macOS Monterey(version 12.4) and a M2 chip. And I have trouble installing PYQt5 as well as Exostriker. The feedback code can be seen from the screenshot below. Thank you!
<img width="1397" alt="Screen Shot 2022-08-12 at 12 10 33 PM" src="https://user-images.githubusercontent.com/111050124/184283887-d00075af-f183-4dda-9da5-391cfe0a0bfe.png">

**Comment by pradyunsg** [comment]
Please reach out to PyQt5 maintainers, for help with understanding why you're unable to install PyQt5: https://www.riverbankcomputing.com/support/pyqt
