### ISSUE TITLE
python2.6 compatible version not available on bootstrap.pypa.io

### ISSUE THREAD

**Issue by joshfriend** [pypa/get-pip#17]
There is a compatibility version for 3.2, but the 2.6 version does not seem to be published

pyenv/pyenv-installer#70

**Comment by pradyunsg** [comment]
It is now. #16

**Comment by joshfriend** [comment]
I do not see a `2.6` directory on https://bootstrap.pypa.io/ and https://bootstrap.pypa.io/2.6/get-pip.py returns a 404.

**Comment by pradyunsg** [comment]
Ah, right. I defer to someone who has access to the server.

**Comment by joshfriend** [comment]
I see the 2.6 version up now, so I'm going to assume that this is resolved.
