### ISSUE TITLE
Python versions being tested by CI don't match noxfile

### ISSUE THREAD

**Issue by pfmoore** [pypa/get-pip#170]
The noxfile has tests for Python versions

```
python=["2.6", "2.7", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9"]
```

The Github Actions CI installs 2.7 and 3.5-3.9. As a result, `nox -s check` fails because 2.6, 3.2, 3.3 and 3.4 are not installed.

We should make nox and CI match.

Also, we should add 3.10, and maybe 3.11.

**Comment by pradyunsg** [comment]
> Python versions being tested by CI don't match noxfile

They don't need to -- they need to be a subset, and unsupported interpreters are the ones that we don't test. Not testing 3.10 and 3.11 is an oversight though, and we should add those in. :)

**Comment by pfmoore** [comment]
I ran `nox -s check` locally and it said:

```
❯ nox -s check
nox > Running session check-2.6
nox > Missing interpreters will error by default on CI systems.
nox > Session check-2.6 skipped: Python interpreter 2.6 not found.
```
See [here](https://nox.thea.codes/en/stable/usage.html#failing-sessions-when-the-interpreter-is-missing) where it mentions that the CI behaviour is different.

**Comment by pradyunsg** [comment]
See #172, where more context was added around this (specifically, nox has changed default behaviours and you need to pass `--no-error-on-missing-interpreters` in CI).
