### ISSUE TITLE
boostrap.pypa's SSL certificate has expired

### ISSUE THREAD

**Issue by d10sfan** [pypa/get-pip#178]
As the title says the url that is recommended to get get-pip.py has an expired SSL certificate:

https://bootstrap.pypa.io/get-pip.py

![image](https://user-images.githubusercontent.com/4337981/214699091-81859143-207f-44df-b2e1-b100159bc7d4.png)

And with wget:

```
+ wget https://bootstrap.pypa.io/get-pip.py
--2023-01-25 21:45:48--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 146.75.28.175, 2a04:4e42:77::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|146.75.28.175|:443... connected.
ERROR: The certificate of 'bootstrap.pypa.io' is not trusted.
ERROR: The certificate of 'bootstrap.pypa.io' has expired.
The certificate has expired
```

**Comment by gaborbernat** [comment]
Cc @ewdurbin

**Comment by ewdurbin** [comment]
working on this now. looks like the CDN issued cert needed a DNS validation update but no notification was sent.

**Comment by pradyunsg** [comment]
Thank you @ewdurbin! ❤️

**Comment by ewdurbin** [comment]
Resolved. Note to self we should move bootstrap.pypa.io to the main PSF fastly account at some point... Its the only remaining service in the PyPA account.
