### ISSUE TITLE
Running get-pip in an environment with no pip installed gives "requirement already satisfied"

### ISSUE THREAD

**Issue by pfmoore** [pypa/get-pip#19]
```
>python .\get-pip.py
Requirement already up-to-date: pip in c:\users\gustav\appdata\local\temp\tmpg92v1j4j\pip.zip (10.0.0)
Collecting setuptools
  Using cached setuptools-39.0.1-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.31.0-py2.py3-none-any.whl
Installing collected packages: setuptools, wheel
Successfully installed setuptools-39.0.1 wheel-0.31.0
```

Using `--force-reinstall` works around this.

**Comment by evgenymarkov** [comment]
It breaks my custom docker image with python today :(

**Comment by dstufft** [comment]
As of https://github.com/pypa/get-pip/commit/ba67ea6b49a0caa1c3be638b9f913590a8af624e this should be fixed, it can take some time for the various automation machinery to pull in the updated ``get-pip.py`` so that it's updated and fixed at ``bootstrap.pypa.io/get-pip.py``.
