### ISSUE TITLE
nox -s generate gives the error "AttributeError: 'HTTPResponse' object has no attribute 'strict'"

### ISSUE THREAD

**Issue by pfmoore** [pypa/get-pip#190]
See https://github.com/ionrock/cachecontrol/issues/293

Pinning "urllib3<2" in the `session.install` of the `generate` session fixes the issue, but I've not created a PR adding this yet, as IMO it would be better if it's fixed in cachecontrol, and we only use this function at release time, so there's no great urgency.

**Comment by sethmlarson** [comment]
I believe this has been fixed upstream in CacheControl (which has moved under the PSF org): https://github.com/psf/cachecontrol/releases/tag/v0.13.1

**Comment by pradyunsg** [comment]
Let's close this out then.
