### ISSUE TITLE
externally-managed-environment

### ISSUE THREAD

**Issue by pratik0007** [pypa/get-pip#197]
python get-pip.py

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by pradyunsg** [comment]
As the message notes:

> If you believe this is a mistake, please contact your Python installation or OS distribution provider.

That is not us.

> See /usr/share/doc/python3.11/README.venv for more information.

Consider reading this document for more details.

---

Assuming you're on Debian/Ubuntu, you likely want to `apt install python3-venv`. See also https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-virtual-environments
