### ISSUE TITLE
not all python version could be found in bootstrap.pypa.io/pip

### ISSUE THREAD

**Issue by Peter33333** [pypa/get-pip#202]
If I am using this on CI flow, so not sure what python version I m handling, but I cant do it like how you 've recommended

`Please use https://bootstrap.pypa.io/pip/{}.{}/get-pip.py instead.".format(*this_python),`

Because not all python version could be found in bootstrap.pypa.io/pip
![image](https://github.com/pypa/get-pip/assets/34623089/b6d7c6d3-9dcd-40c7-b601-57800e10b621)

Do I describe clearly? Please help.

**Comment by pradyunsg** [comment]
Duplicate of #88
