### ISSUE TITLE
get-pip.py script not compatible with Python 3.7

### ISSUE THREAD

**Issue by fti-sfuke** [pypa/get-pip#214]
### Description:

When attempting to install `pip` using the `get-pip.py` script from `https://bootstrap.pypa.io/get-pip.py` on a system running Python 3.7, an error message is displayed indicating that the script requires a minimum Python version of 3.8.

#### Error Message:
```plaintext
ERROR: This script does not work on Python 3.7 The minimum supported Python version is 3.8
```

#### Steps to reproduce
```
# wget  -q --timeout 10 -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py

# python3 /tmp/get-pip.py
----------------------------------------
ERROR: This script does not work on Python 3.7 The minimum supported Python version is 3.8. Please use https://bootstrap.pypa.io/pip/3.7/get-pip.py instead.
```

### Environment:
**Python version:**

```
#python3 --version
Python 3.7.3
```
**OS Details:**
```
Debian GNU/Linux 10 (buster)
```

**Kernel Version :** 
```
# uname -a
Linux DEB-NUC8i3BE-G6Bxx 5.10.0-0.deb10.16-amd64 #1 SMP Debian 5.10.127-2~bpo10+1 (2022-07-28) x86_64 GNU/Linux
```

**Comment by edmorley** [comment]
@fti-sfuke Hi. 

This is expected - Python 3.7 is EOL and so the latest version of Pip doesn't support it.

Please read the error message, which explains this pretty clearly how to avoid it:

```
ERROR: This script does not work on Python 3.7 The minimum supported Python version is 3.8. 
Please use https://bootstrap.pypa.io/pip/3.7/get-pip.py instead.
```

**Comment by fti-sfuke** [comment]
@edmorley 
Thanks for the update. Apologies for the oversight. I didn't read the complete error message.

I was able to fix the issue by changing the URL from `https://bootstrap.pypa.io/get-pip.py` to `https://bootstrap.pypa.io/pip/3.7/get-pip.py`.

Is my understanding correct that now `https://bootstrap.pypa.io/pip/get-pip.py` only supports Python 3.8 and above, and for older versions like 3.7, you have categorized the `get-pip.py` based on the Python version?

**Comment by edmorley** [comment]
Yeah that's correct :-)

**Comment by fti-sfuke** [comment]
Thank you for confirming.
I am closing this issue now.

**Comment by fti-sfuke** [comment]
@edmorley 
Thank you for confirming.
I am closing this issue now.
