### ISSUE TITLE
ERROR: To modify pip, please run the following command

### ISSUE THREAD

**Issue by whitedwarfsun** [pypa/get-pip#27]
When I try to install _pip_ using `get-pip.py` from https://bootstrap.pypa.io/get-pip.py I get
```
ERROR: To modify pip, please run the following command:
C:\Python27\python.exe -m pip
```

I am on Win10 1703.15063 and have Python 2.7.8 32-bit installed in `C:\Python27\python.exe`.

**Comment by whitedwarfsun** [comment]
I was finally able to install _pip_ using the 2.6 version of `get-pip.py`, i.e. https://bootstrap.pypa.io/2.6/get-pip.py.

For future reference:
```
29af88001263a19911c0911057cc192e  ./get-pip.py      did *not* work for me,
e4bd67ad4de5329bd4291e06ee3ba012  ./2.6/get-pip.py  *did* work for me.
```

**Comment by webknjaz** [comment]
#25 will fix this

**Comment by pradyunsg** [comment]
This has been fixed. If you try again with the latest script, it should work. :)

**Comment by pradyunsg** [comment]
Thanks for filing this issue @whitedwarfsun! :)
