### ISSUE TITLE
bootstrap.pypa.io not responding

### ISSUE THREAD

**Issue by timojuonoja** [pypa/get-pip#34]
https://bootstrap.pypa.io/

Server responds with "503 Service Unavailable".

**Comment by mayait** [comment]
Any workaround or mirror?

**Comment by mayait** [comment]
Alternative location for get-pip.py: https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py

**Comment by ewdurbin** [comment]
Resolved. The host that serves this content kernel panicked. It's been rebooted.
