### ISSUE TITLE
get-pip no longer works with explicit args for pip

### ISSUE THREAD

**Issue by mihnea-dobrescubalaur-hs** [pypa/get-pip#37]
Hi!

Try `curl https://bootstrap.pypa.io/get-pip.py | python - pip==18.0` and you will see that a `DoubleRequirement` exception is thrown. If you debug a bit, you'll find that actually `InstallRequirement.from_line` fails (`InstallRequirement` does not have `from_line`) and that triggers the `continue` call in the loop.

Thanks!

**Comment by rbreslow** [comment]
I'm also getting this. Our Ansible provisioning that uses `get-pip.py` is broken. https://github.com/azavea/ansible-pip

**Comment by benoit-pierre** [comment]
See https://github.com/pypa/pip/issues/5857

**Comment by benoit-pierre** [comment]
As a temporary workaround, you can use a constraint, e.g.: `python get-pip.py -c <(echo 'pip==18.0')`.

**Comment by cloneluke** [comment]
duplicate: https://github.com/pypa/pip/issues/5859

**Comment by pradyunsg** [comment]
Thanks @benoit-pierre for the investigation and PR! :)

This didn't show up in my manual "does it install pip on running?" check for `get-pip.py` prior to the release.

I guess it shows we really need to do #18. Help on that front would be appreciated. :)
