### ISSUE TITLE
current get_pip requires distutils.util - ubuntu18.04

### ISSUE THREAD

**Issue by ITJamie** [pypa/get-pip#44]
can the install of this not be done in the script?

```
/usr/bin/python3.6 get-pip.py --upgrade --force-reinstall
Traceback (most recent call last):
  File "get-pip.py", line 21492, in <module>
    main()
  File "get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal
  File "/tmp/tmp2eupwih9/pip.zip/pip/_internal/__init__.py", line 40, in <module>
  File "/tmp/tmp2eupwih9/pip.zip/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/tmp/tmp2eupwih9/pip.zip/pip/_internal/cli/main_parser.py", line 8, in <module>
  File "/tmp/tmp2eupwih9/pip.zip/pip/_internal/cli/cmdoptions.py", line 14, in <module>
ModuleNotFoundError: No module named 'distutils.util'
```

**Comment by ITJamie** [comment]
Its been reported here in a closed issue also
https://github.com/pypa/get-pip/issues/43#issuecomment-500807057

**Comment by pradyunsg** [comment]
Thanks for filing this!

As you noticed, Ubuntu ships their Python with a different structure, omitting parts of the standard library that pip depends on. 

The best course of action here is to voice this concern and provide feedback to Ubuntu about this.

Oh, and `apt install python-distutils`. ;)

**Comment by antoineFrau** [comment]
Hello, I have the same issue, trying to use get-pip.py with python3.6 and having the same error : 

`ModuleNotFoundError: No module named 'distutils.util'`

So I try to run the command : 

`sudo apt install python3-distutils` 

But that's telling me that will install python3.7
```
pi@raspberrypi:~ $ sudo apt install python3-distutils
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib python3 python3-lib2to3 python3-minimal python3.7 python3.7-minimal
Suggested packages:
  python3-doc python3-tk python3-venv python3.7-venv python3.7-doc binfmt-support
The following NEW packages will be installed:
  libpython3-stdlib libpython3.7-minimal libpython3.7-stdlib python3 python3-distutils python3-lib2to3 python3-minimal python3.7 python3.7-minimal
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 4377 kB of archives.
After this operation, 22.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

So how does it works ? Does I need to install python3.7 to install pip for python3.6 ?

Thanks.

**Comment by selyunin** [comment]
Hi, I got the same problem, and this answer helped: https://github.com/pypa/get-pip/issues/43#issuecomment-513503447

https://github.com/pypa/get-pip/issues/43#issuecomment-513503447

As root:
```
apt-get download python3-distutils
dpkg-deb -x ./python3-distutils_3.6.9-1~18.04_all.deb /
python3.7 get-pip.py
```

**Comment by insanansharyrasul** [comment]
> Hi, I got the same problem, and this answer helped: [#43 (comment)](https://github.com/pypa/get-pip/issues/43#issuecomment-513503447)
> 
> [#43 (comment)](https://github.com/pypa/get-pip/issues/43#issuecomment-513503447)
> 
> As root:
> 
> ```
> apt-get download python3-distutils
> dpkg-deb -x ./python3-distutils_3.6.9-1~18.04_all.deb /
> python3.7 get-pip.py
> ```
How about without root? i don't have root previleges.

**Comment by RubiksMaster3x3** [comment]
> Hi, I got the same problem, and this answer helped: [#43 (comment)](https://github.com/pypa/get-pip/issues/43#issuecomment-513503447)
> 
> [#43 (comment)](https://github.com/pypa/get-pip/issues/43#issuecomment-513503447)
> 
> As root:
> 
> ```
> apt-get download python3-distutils
> dpkg-deb -x ./python3-distutils_3.6.9-1~18.04_all.deb /
> python3.7 get-pip.py
> ```
I am actually on kali linux, but I can't find any info about this topic for anything other than ubuntu. When I try the first command I get this error: 
"Can't select candidate version from package python3-distutils as it has no candidate"
Do you have any idea as to what I can do?

**Comment by sjatkins** [comment]
I don't understand what that second line is supposed to be doing. why the ending /?  And why oh why is something so basic to many tools not installed? Do they want people, even those that have used linux for years, to hate it?  Everything was fine on my system until last ubuntu upgrade that threw away such things. Now I am hosed on tools that depend on this.

**Comment by selyunin** [comment]
It ends with `/` as the `dpkg-deb -x` extracts the content of the `*.deb` file to a directory, and the last comand argument where it shall be extracted. You can extract to current directory with `./` instead of `/`. It worked for me, that's why I shared this as is.
