### ISSUE TITLE
Provide the 3.4 specific version on bootstrap.pypa.io

### ISSUE THREAD

**Issue by behackett** [pypa/get-pip#50]
Similar to the versions for 2.6, 3.2 and 3.3.

**Comment by pradyunsg** [comment]
Hmm...

@ewdurbin could you look into why 3.4/get-pip.py hasn't been reflected from here to bootstrap.pypa.io?

**Comment by ewdurbin** [comment]
This should be good to go now.

Perhaps the necessary bits in python/psf-salt should be slightly more automated. I've filed an issue to track that.

**Comment by pradyunsg** [comment]
@ewdurbin Thanks!

**Comment by behackett** [comment]
Thanks for the quick turnaround!
