### ISSUE TITLE
Unable to install pip on HP-UX

### ISSUE THREAD

**Issue by tamil07** [pypa/get-pip#55]
Team,

I am trying to install pip on a HP UX machine. Available python versions for HP-UX are 2.7.* - You may verify the same here - http://hpux.connect.org.uk/hppd/cgi-bin/search?term=python&Search=Search 

I tried by downloading the pip file and below is the error.

# /usr/local/bin/python get-pip.py
Collecting pip<10
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x9fffffffeea2ae10>: Failed to establish a new connection: [Errno -1] ',)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x9fffffffeea2a110>: Failed to establish a new connection: [Errno -1] ',)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x9fffffffeea2abd0>: Failed to establish a new connection: [Errno -1] ',)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x9fffffffeea2aa90>: Failed to establish a new connection: [Errno -1] ',)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x9fffffffeea2a8d0>: Failed to establish a new connection: [Errno -1] ',)': /simple/pip/
  Could not find a version that satisfies the requirement pip<10 (from versions: )
No matching distribution found for pip<10
# uname -a
HP-UX lqam8082 B.11.31 U ia64 1404401316 unlimited-user license
# python --version
Python 2.7.16
#

**Comment by chrahunt** [comment]
This kind of generic connection error is going to be specific to your environment, system configuration, and/or network configuration. I would suggest bringing your query to one of the [stack exchange](https://stackexchange.com/sites#) sites (maybe Server Fault or Unix & Linux). They would be able to give you more prompt attention.

Since this isn't specific to pip (or get-pip) I will close this issue.
