### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by Czaki** [pypa/get-pip#56]
If it is possible to add tags for get_pip releases? Currently, if there is need to get deterministic build (continuous integration) the there is need to pin with commit hash which is unreadable for human.

**Comment by lobsterdore** [comment]
I second this, after towards outage I think we need a guaranteed way to get older versions of pip, tagging get-pip for the version that it comes bundled with would be great.

**Comment by Flamefire** [comment]
Yes please. Having releases with a known SHA-256 of get-pip.py (the final version) would be great for security and reproducibility.

**Comment by pradyunsg** [comment]
> If it is possible to add tags for get_pip releases?

I've gone ahead and done this for pip 20.1 (released just now). I don't want to go back and tag existing releases, and we'd likely need to want to add automation for these releases TBH.

**Comment by pradyunsg** [comment]
Closing since we've added these for recent releases, and I don't think we should be back-filling here.
