### ISSUE TITLE
How is this project licensed?

### ISSUE THREAD

**Issue by camelaissani** [pypa/get-pip#6]
What's the license for this project?
Do you have a specific release version for this tool?
Thanks

**Comment by xavfernandez** [comment]
Since this was extracted from the https://github.com/pypa/pip repo it is likely MIT licensed.
I agree, a LICENSE file would be clearer.

**Comment by camelaissani** [comment]
I'm asking because we would store it in our corporate repository (not PYPI).
What about the version?

**Comment by xavfernandez** [comment]
cc @dstufft since you created this repo.
Could you confirm it is MIT licensed ?

**Comment by pradyunsg** [comment]
I filed #49 to note that this is licensed under MIT (w/ the same license text as pip's).
