### ISSUE TITLE
Runtime error in carla 0.9.5 and 0.9.4 on windows 10

### ISSUE THREAD

**Issue by xusafzai** [pypa/get-pip#66]
Hi, i'm getting these errors alternatively while running my program in Carla. 
either I get this error:
"RuntimeError: failed to connect to newly created map"
or this:
"RuntimeError: time-out of 20000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000"
Also I have both versions 0.9.5 and 0.9.4 but in version 0.9.4 i'm can't find any file named "Carla" and "EGG INFO" in python API.
i'm attaching the code If someone wants to have a look.
[code.txt](https://github.com/pypa/get-pip/files/4705376/code.txt)
@BrandonHaynes @nsubiron help plz

**Comment by BrandonHaynes** [comment]
You'll want to create this issue in the Carla repository: https://github.com/carla-simulator/carla
