### ISSUE TITLE
Non-ascii error on vagrant command

### ISSUE THREAD

**Issue by michaelsilao** [pypa/get-pip#67]
Hi,

Im getting this error when running vagrant up. and similarly when I try to ssh in to the vagrant machine and run the curl command. Has anyone encountered this kind of issue or could share a solution. Thanks in advance

curl https://bootstrap.pypa.io/get-pip.py | sudo python

Stdout from the command:

Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  File "<stdin>", line 1083
SyntaxError: Non-ASCII character '\xc6' in file <stdin> on line 1084, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
  5 1825k    5  100k    0     0   113k      0  0:00:16 --:--:--  0:00:16  113k
curl: (23) Failed writing body (946 != 1371)

**Comment by agoradesign** [comment]
same problem.. no idea how to solve :(

**Comment by byronwade** [comment]
same problem

**Comment by luciof5** [comment]
same problem

**Comment by pradyunsg** [comment]
Don't use `curl ... | python` -- please follow the instructions at https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py for using this script.
