### ISSUE TITLE
Update location of get-pip in the template 

### ISSUE THREAD

**Issue by oz123** [pypa/get-pip#71]
The header for `get-pip.py` is quite outdated since it's mentioning that:

>  If you're wondering how this is created, it is using an invoke task located
>  in tasks/generate.py called "installer". It can be invoked by using
> ``invoke generate.installer``.

To a newcomer it seems that this code lives in the main repository of pip, however since 2016 (git commit 3c753c5a86303dd012a96e60013b216ebb85edbe in pipenv) this is no longer the case and the code lives here.
IMO this should be updated in the code comment to something like:

>  If you're wondering how this is created, it is using an invoke task located
>  in https://github.com/pypa/get-pip/tasks/generate.py called "installer". It can be invoked by using
> ``invoke generate.installer``.

Will you accept a PR for this?

**Comment by pradyunsg** [comment]
This has been updated in #100.
