### ISSUE TITLE
on windows running get-pip does absolutely nothing both through CMD and PS.

### ISSUE THREAD

**Issue by M1ghty-boy** [pypa/get-pip#74]
Running `py get-pip.py` just returns to the next line in CMD and PS and does nothing else. am not sure how to solve this as nothing is working and i can't find any solutions

**Comment by pradyunsg** [comment]
Hi! It might be that the Windows Store window for installing Python has opened.

None the less, I think that [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [StackOverflow](https://stackoverflow.com) would be better channels to get support for the issue you're facing.
