### ISSUE TITLE
Web scraping with different urls

### ISSUE THREAD

**Issue by pietrakneib** [pypa/get-pip#76]
I've wrote this code to do a web scraping with 20 different pages (urls), the problem is since the urls are different, I need to do a loop with a list of links and a loop to do the web scraping in each page. My problem is when I do like this, I get the loop with the pages, but python only give me the first information in each page ( does not run the loop in each page, to get all the informations). Can you help? 

from bs4 import BeautifulSoup
import requests
import csv
import pandas as pd
from random import randint
from time import sleep

empresa = []
saida = []
chegada = []
origem = []
destino = []
price = []
classe = []

filename="raspagem2.csv"
f=open(filename,"w")

headers = "Empresa; Saída; Chegada; Origem; Destino; Preço; Classe\n"
f.write(headers)

lista_urls=["https://www.clickbus.com.br/onibus/sao-paulo-tiete-sp/parati-rj",
"https://www.clickbus.com.br/onibus/sao-paulo-tiete-sp/rio-de-janeiro-rj",
"https://www.clickbus.com.br/onibus/curitiba-pr/sao-paulo-sp-todos",
"https://www.clickbus.com.br/onibus/belo-horizonte-mg-todos/rio-de-janeiro-rj-todos",
"https://www.clickbus.com.br/onibus/rio-de-janeiro-rj/campinas-sp",
"https://www.clickbus.com.br/onibus/belo-horizonte-mg/sao-paulo-tiete-sp",
"https://www.clickbus.com.br/onibus/goiania-go/brasilia-df",
"https://www.clickbus.com.br/onibus/sao-paulo-tiete-sp/ribeirao-preto-sp",
"https://www.clickbus.com.br/onibus/sao-paulo-tiete-sp/brasilia-df",
"https://www.clickbus.com.br/onibus/porto-alegre-rs/florianopolis-sc",
"https://www.clickbus.com.br/onibus/sao-paulo-tiete-sp/florianopolis-sc",
"https://www.clickbus.com.br/onibus/sao-paulo-barra-funda-sp/sao-jose-do-rio-preto-sp",
"https://www.clickbus.com.br/onibus/campinas-sp/rio-de-janeiro-rj",
"https://www.clickbus.com.br/onibus/florianopolis-sc/porto-alegre-rs",
"https://www.clickbus.com.br/onibus/curitiba-pr/florianopolis-sc",
"https://www.clickbus.com.br/onibus/brasilia-df/goiania-go",
"https://www.clickbus.com.br/onibus/rio-de-janeiro-rj-todos/belo-horizonte-mg",
"https://www.clickbus.com.br/onibus/sao-paulo-sp-todos/curitiba-pr",
"https://www.clickbus.com.br/onibus/rio-de-janeiro-rj/sao-paulo-tiete-sp",
"https://www.clickbus.com.br/onibus/florianopolis-sc/sao-paulo-tiete-sp"]

for elem in lista_urls: 
    
    response = requests.get(elem)
    
    soup=BeautifulSoup(response.content, 'html.parser')
    
    containers=soup.findAll("div",{"class":"search-result-item valign-wrapper"})
    
    sleep(randint(2,10)
                  
    
    for container in containers:
        
        empresa = container.find('div',{"class":"company"}).img["alt"]                            
        saida = container.find('time',{"class":"departure-time"}).text
        chegada = container.find('time',{"class":"return-time"}).text
        origem = container.find('span',{"class":"station-departure"}).text
        destino = container.find('span',{"class":"station-arrival"}).text
        price=container.find('span',{"class":"price-value"}).text
        classe = container.find('div',{"class":"service-class"}).span.text
    
    f.write(empresa + ";" + saida + ";" + chegada + ";" + origem + ";" + destino + ";" + price + ";" + classe + "\n") 
    
f.close()

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this but this isn't the right place for this issue.

I think that [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [Code Review](https://codereview.stackexchange.com/) would be better channels to get the help you are looking for. :)
