### ISSUE TITLE
Python 2.7 Broken

### ISSUE THREAD

**Issue by soofgo** [pypa/get-pip#82]
Latest commit broke python 2.7 compatibility over string formatting :(

```
python2.7 get-pip.py
Traceback (most recent call last):
    File "get-pip.py", line 24226, in <module>
        main()
    File "get-pip.py", line 199, in main
        bootstrap(tmpdir=tmpdir)
    File "get-pip.py", line 82, in bootstrap
        from pip._internal.cli.main import main as pip_entry_point
    File "/tmp/tmpO8Gfeg/pip.zip/pip/_internal/cli/main.py", line 60
        sys.stderr.write(f"ERROR: {exc}")
        ^

SyntaxError: invalid syntax
```

**Comment by soofgo** [comment]
pip 21.0 removes python2.7 support

**Comment by pradyunsg** [comment]
Please use https://bootstrap.pypa.io/2.7/get-pip.py.

**Comment by soofgo** [comment]
Thanks :)

**Comment by webknjaz** [comment]
@pradyunsg did you consider enabling discussions on this repo? This could be useful in the Q&A format.

**Comment by taro-spb** [comment]
@pradyunsg  Will subdirectory `2.7/` be left upstream forever or are there any plans to remove it in the future?

**Comment by b4cktr4ck2** [comment]
Just had this issue on an up-to-date Kali Linux installation with Python 2.7.18- the url @pradyunsg specified worked for me.

**Comment by pradyunsg** [comment]
@taro-spb there are no plans at this time to remove that script.

**Comment by matthewfeickert** [comment]
> @pradyunsg Will subdirectory `2.7/` be left upstream forever or are there any plans to remove it in the future?
>...
> @taro-spb there are no plans at this time to remove that script.

@pradyunsg @webknjaz Apologies in advance if you'd really prefer to not have continuation of discussion on closed Issues (I'm happy to open a new one instead), but I noticed today that the `2.7/` subdirectory has been removed 

```console
$ docker run --rm -ti python:2.7 /bin/bash
root@1a9208fd00d3:/# curl -sLO https://bootstrap.pypa.io/2.7/virtualenv.pyz
root@1a9208fd00d3:/# cat virtualenv.pyz 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@1a9208fd00d3:/# curl -sLO https://bootstrap.pypa.io/2.7/get-pip.py
root@1a9208fd00d3:/# cat get-pip.py 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@1a9208fd00d3:/# 
```

...though I guess just looking at the index of https://bootstrap.pypa.io/ would have told me this as well.

![index](https://user-images.githubusercontent.com/5142394/159524082-0989b3d5-95c9-4d3c-8902-ac52f38e37a1.png)

Apologies as well for bringing up a Python 2 issue. I'm not actively trying to still use it :slightly_frowning_face:, but my physics collaboration has some of [our software stack locked to it](https://github.com/matthewfeickert/cvmfs-venv/issues/6).

**Comment by pradyunsg** [comment]
https://github.com/pypa/get-pip/commit/b44c5248c6916cbfa650e419fc8fb9ed39dd6a44 was the commit that provided a helpful message to users when this was migrated. That was reverted after a grace period.

**Comment by matthewfeickert** [comment]
Excellent. Thanks very much for this helpful information and for taking the time to reply!
