### ISSUE TITLE
WARNING: request for update pip version 20.3.4; to 21.0 

### ISSUE THREAD

**Issue by geethupendra** [pypa/get-pip#91]
Hello,

When installing the pip (2.7), it's asking for the version update (WARNING: You are using pip version 20.3.4; however, version 21.0 is available.)...
is there any command update for the versions...

root@ip-xxxx:~# curl https://bootstrap.pypa.io/2.7/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1863k  100 1863k    0     0  6090k      0 --:--:-- --:--:-- --:--:-- 6090k
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pip<21.0
  Downloading pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 24.0 MB/s
Collecting setuptools<45
  Downloading setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
     |████████████████████████████████| 583 kB 80.1 MB/s
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-20.3.4 setuptools-44.1.1 wheel-0.36.2
WARNING: You are using pip version 20.3.4; however, version 21.0 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.

Thanks
Geeth

**Comment by webknjaz** [comment]
That's coming from pip itself, not `get-pip.py`. I don't think there is anything actionable here.

**Comment by geethupendra** [comment]
Ok Thanks
